use serde::{Deserialize, Serialize};

/// Uniquely identifies a single metric within its metric type.
#[derive(Debug, PartialEq, Eq, Hash, Copy, Clone, Deserialize, Serialize)]
#[repr(transparent)]
pub struct MetricId(pub(crate) u32);

impl MetricId {
    pub fn new(id: u32) -> Self {
        Self(id)
    }
}

impl From<u32> for MetricId {
    fn from(id: u32) -> Self {
        Self(id)
    }
}

// Metrics generated by the Glean Rust SDK parser implementation
pub mod og_metrics {
    include!(concat!(env!("OUT_DIR"), "/glean_metrics.rs"));
}

// Metrics generated by us!
pub mod generated {
    include!("./generated/metrics.rs");
    include!("./generated/pings.rs");
}
